site:
  title: Pre-Crime Application Docs
  url: https://raphael74.github.io/pre-crime-app
  start_page: developer-docs::index.adoc

content:
  sources:
    - url: ./
      branches: HEAD
      start_path: etc/developer-docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./build/site
