spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="precrime"
        password="precrime-secret";
    admin:
      properties:
        sasl.jaas.config: >
          org.apache.kafka.common.security.plain.PlainLoginModule required
          username="admin"
          password="admin-secret";
  datasource:
    url: jdbc:postgresql://localhost:5432/precrime
    username: precrime_app
    password: app_pass
  flyway:
    user: precrime_migration
    password: migration_pass
    clean-disabled: false
precrime:
  flyway:
    clean-on-validation-error: true
logging:
  level:
    ch.ejpd.example.precrime: DEBUG
