spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/precrime
    username: precrime_app
    password: app_pass
  flyway:
    user: precrime_migration
    password: migration_pass
    clean-disabled: false
precrime:
  flyway:
    clean-on-validation-error: true
logging:
  level:
    ch.ejpd.example.precrime: DEBUG
