spring:
  application:
    name: pre-crime-app
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: true
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "ch.ejpd.example.precrime.*"
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    clean-disabled: true
jooq:
  sql-dialect: postgres
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
precrime:
  flyway:
    clean-on-validation-error: false
logging:
  level:
    org.jooq: INFO
    org.flywaydb: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
    kafka: WARN
    state.change.logger: WARN
    org.jooq.Constants: off
